### ISSUE TITLE
Resolve the differences in calculating ybus

### ISSUE THREAD

**Issue by poorva1209** [GRIDAPPSD/gridappsd-distributed-static-ybus-service#4]
- for admittance between the centralized ybus and distributed algo

**Comment by poorva1209** [comment]
- Document the expected differences between centralized and distributed ybus response in README

**Comment by poorva1209** [comment]
- There are some expected differences: There are minor changes because Feeder sees all equipment (Feeder sees switch) and distributed areas don't see boundary equipment (do not see switch). 
- Still need to figure out ~1% difference in some values. (missing self admittance may be)

**Comment by afisher1** [comment]
The issue is that some Ybus calculations require the query results to be ordered by name and then by phase. This ordering is not possible with the current cim-graph implementation so I am sorting the query results before processing them in the in the ybus service. 

Current testing only shows differences due to feeder Level Ybus not containing switch area capacitor equipment contributions and switch level Ybus not containing feeder area switch equipment contributions. This is to be expected with the current limitations of how unaddressable and addressable equipment for each area is implemented.
